SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
INSERT OVERWRITE TABLE CDW_SAPP_D_BRANCH
PARTITION (BRANCH_STATE)
SELECT BRANCH_CODE,
BRANCH_NAME, 
BRANCH_STREET,
BRANCH_CITY,
BRANCH_ZIP,
BRANCH_PHONE, 
LAST_UPDATED,
BRANCH_STATE

from CDW_SAPP_D_BRANCH_ONE;