DROP TABLE CDW_SAPP_D_BRANCH;

SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;

CREATE  EXTERNAL TABLE CDW_SAPP_D_BRANCH
(BRANCH_CODE int, 
BRANCH_NAME string, 
BRANCH_STREET string, 
BRANCH_CITY string, 
BRANCH_ZIP int, 
BRANCH_PHONE string , 
LAST_UPDATED timestamp) 
PARTITIONED BY (BRANCH_STATE string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' ESCAPED BY '"' LINES TERMINATED BY '\n'

LOCATION "/user/maria_dev/Credit_Card_System/CDW_SAPP_D_BRANCH10";