SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
INSERT OVERWRITE TABLE CDW_SAPP_F_CREDIT_CARD
PARTITION (BRANCH_CODE)
SELECT CUST_CC_NO,
TIMEID,
CUST_SSN,
TRANSACTION_TYPE,
TRANSACTION_VALUE,
LAST_UPDATED,
BRANCH_CODE

from CDW_SAPP_F_CREDIT_CARD_ONE;